### ISSUE TITLE
数据集分集问题

### ISSUE THREAD

**Issue by H3IIoWorld** [tommy-xq/SA2VP#1]
datasets.py line 798，请问为什么这里把val200.txt设成是test集了呀？复现发现vtab每次都100acc（0.o）

**Comment by tommy-xq** [comment]
@H3IIoWorld Thank you for your interest in our work. 对于FGVC来说，通用做法是train set训练时在val set上找最好的模型，然后去test上测试，训练可以用--my_mode train_val来设置；对于VTAB-1k，需要使用train_val(800 200)来人工寻找最好的训练配置(如lr、weight_decay等，尽可能让模型最后收敛时的效果好)，确定配置后使用trainval_test来训练，取最后训练完的模型去test上测试，每次训完都会测试让整个流程时间有些久。这里把val200.txt设成是test集只是为了训练快些，训练时几乎省略test，训练完成后再去test上测。
（1）vtab上测试可用：
CUDA_VISIBLE_DEVICES=1 python vit_train_sa2vp.py --data_set DS_LOC --eval  --batch_size 64 --resume ./model_save/DS_LOC/checkpoint-99.pth --nb_classes 16 --my_mode trainval_test
（2）fgvc上测试把checkpoint-99.pth替换为checkpoint-best.pth即可。

**Comment by H3IIoWorld** [comment]
No wonder!!非常感谢！好人一生平安！
